### ISSUE TITLE
Add a hamburger menu to mobil view

### ISSUE THREAD

**Issue by willnickerson** [GloriaAnholt/ClassAssignments#6]
When the page becomes narrower and the nav becomes vertically displayed, it takes up almost hald the page. You should consider adding a hamburger menu that hides the nav when you reach your narrower breakpoints.

**Comment by GloriaAnholt** [comment]
This needs the icomoon vector graphic functionality to be deeper dived into. Saving as a TODO.

**Comment by GloriaAnholt** [comment]
There's now a menu only in the smallest render size - tab bar appears in larger views.
